### ISSUE TITLE
how to execute

### ISSUE THREAD

**Issue by Marikantitarun** [pierregoaer/advanced_flask_mysql_sign_up_log_in#1]
how do i execute this whole website?

**Comment by pierregoaer** [comment]
You have 2 options:
- Use the command `Flask run` in your terminal
- Use `app.run()` (it's the one I use in this case). In your app file, add the following at the end of your code:

```
if __name__ == "__main__":
    app.run()
```

You will also need to create your own MySQL database with your own credentials, server and database. These are saved as environment variables so they are not publicly shared here on GitHub.

Hope this helps, let me know if you have any questions.

**Comment by Marikantitarun** [comment]
Please dont mind me..Actually, can you make a short video on how to execute it?

**Comment by pierregoaer** [comment]
What exactly would you like to see? I'm happy to help you make this run if you can describe where you're having issues executing it, I can then make a specific video.
